live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "On"
shape = "Underline"

[selection]
save_to_clipboard = false

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
dynamic_padding = true

[window.padding]
x = 17
y = 17
