live_config_reload = true

[font]
size = 8

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x=0
y=0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 0
